### ISSUE TITLE
Permission Issue :Failed to open network adapter

### ISSUE THREAD

**Issue by megachweng** [w1ndy/OS-X-H3CClient#5]
<pre>
2016-10-20 01:55:28.688 RealiNode[670:14566] connecting...
2016-10-20 01:55:28.689 RealiNode[670:14566] opening adapter en0...
2016-10-20 01:55:28.689 RealiNode[670:14566] pcap_open_live() error: en0: You don't have permission to capture on that device ((cannot open BPF device) /dev/bpf4: Permission denied)
</pre>

occurred after a power cut

and also bring a another problem [upperLimit](https://github.com/w1ndy/OS-X-H3CClient/issues/6)

**Comment by guoye-zhang** [comment]
`sudo launchctl unload /Library/LaunchDaemons/org.wireshark.ChmodBPF.plist`
`sudo launchctl load /Library/LaunchDaemons/org.wireshark.ChmodBPF.plist`

**Comment by megachweng** [comment]
@cc941201 thx It works

what about execute those command in  program initiation @w1ndy ?

**Comment by guoye-zhang** [comment]
This is a known issue. This plist is loaded when macOS starts, but when network configuration changes (for example plugging in Thunderbolt Ethernet Adapter), it has to be run again.

Note that this script needs root privilege, so you'll have to input your password each time it is run.

**Comment by w1ndy** [comment]
@megachweng [org.wireshark.ChmodBPF.plist](https://github.com/w1ndy/OS-X-H3CClient/blob/master/OS-X-H3CClient/org.wireshark.ChmodBPF.plist) is a script taken from Wireshark that will enable privileges for applications on BPF devices every time the system boots. As @cc941201 says, not executing the script during the application startup is by design so you won't have to enter root password frequently.
